version: "3.9"

services:
  travel-site:                        # Nginx: serves /public
    image: nginx:alpine
    container_name: travel-site
    ports:
      - "8080:80"                     # http://truenas.local:8080
    volumes:
      - ./public:/usr/share/nginx/html:ro
    restart: unless-stopped

  travel-api:                         # Fastify backend
    image: node:20-alpine
    container_name: travel-api
    working_dir: /app
    command: |
      sh -c "
        npm install &&
        PORT=4000 \
        REPO_DIR=/app \
        GIT_USER_NAME='Your Name' \
        GIT_USER_EMAIL='you@example.com' \
        node server.js
      "
    ports:
      - "4000:4000"                   # http://truenas.local:4000
    volumes:
      - ./:/app
    restart: unless-stopped
    environment:
      # Uncomment and set if you want automatic git push
      # GITHUB_TOKEN: ghp_your_personal_access_token
      # GIT_PUSH: "true"              # default is true
